Feat/initial
Hexastack/hexabot-channel-whatsapp pull request #1
Opened 2024-11-27 17:35 UTC by Emnaghz

2024-12-11 16:50 UTC, marrouchi requested changes

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +      case OutgoingMessageFormat.list:
```suggestion
      case OutgoingMessageFormat.carousel:
      case OutgoingMessageFormat.list:
```

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +
Let's add comments (compodoc) to each function

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +    );
I think you need to update config.apiUrl which is a env var : NGROK url.

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +              title: 'Title',
Let's replace by the content type name ?

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +  }
```suggestion
  _carouselFormat() {
    throw new Error('Method not supported yet.');
  }
```

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +    const message = handler._formatMessage(
```suggestion
    const handler: WhatsappHandler = this;
    const message = handler._formatMessage(
```
```suggestion
    const message = this._formatMessage(
```

2024-12-11 16:50 UTC, marrouchi commented on index.channel.ts
> +  //TODO onevent update setting (hook:setting:postUpdate)
```suggestion
```

2024-12-11 16:50 UTC, marrouchi commented on lib/graph-api.ts
> +    );
this.httpService.axiosRef.request()

2024-12-11 16:50 UTC, marrouchi commented on README.md
> +The Whatsapp Channel Extension for Hexabot Chatbot / Agent Builder
Let's document every configuration 🙏

2024-12-16 15:55 UTC, Emnaghz commented on index.channel.ts
> +              title: 'Title',
the content type isn't returned in the envelope(maybe it should be fixed/added in the future), however I will eliminate the 'Title' to avoid any confusion
![image](https://github.com/user-attachments/assets/1a04a9a0-1cd2-4e50-8226-e096e652504f)

2024-12-20 15:04 UTC, merged